spring.application.name=backend
spring.config.import=optional:file:.env[.properties]
# Server Configuration
server.port=8080

# max payload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=-1
server.tomcat.websocket.max-text-message-size=10485760
server.tomcat.websocket.max-binary-message-size=10485760
spring.websocket.max-text-message-size=10485760
spring.websocket.max-binary-message-size=10485760

# Database Configuration (Using MySQL)
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Console (Accessible at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Custom Security properties (e.g. JWT secret key)
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}
    
# ==========================================
# GMAIL SMTP DISPATCH CONFIGURATION
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
